version: 1.0.0
name: new
apps:
  - uuid: 0f35e436-bb20-11f0-90ab-dfa030750795
    release: 0.1.0
  - uuid: 4492ab62-bb1d-11f0-ba61-eb4ead23902e
    release: latest
  - uuid: 5a86baa4-b360-11f0-9b56-1b25900fef4a
    release: latest
  - uuid: 60b24634-b110-11f0-9087-af5f4f5c0f90
    release: 1.0.0
  - uuid: 639c126a-b8f6-11f0-bfe6-03ee3e26a895
    release: 3.0.0
  - uuid: b372f3bc-b450-11f0-9ed1-b7a400795c51
    release: latest
  - uuid: e5608fa2-d137-11f0-b7bd-1b9599cf413b
    release: latest
